### ISSUE TITLE
Question: Is there a way to make the highlights persist after restarting Visual Studio Code?

### ISSUE THREAD

**Issue by marykaw** [BrandonBlaschke/vscode-easy-highlight#10]
Is there perhaps a way to do this?   All highlights in a file are gone after restarting Visual Studio Code.
Opening and closing the file works perfect as long as Visual Studio Code is not exited.

**Comment by BrandonBlaschke** [comment]
Hi Marykaw,

It should already save your highlights for the project folder. I just tried making highlights and closing VSCode and they still appear upon startup. However, if you open the same file from a different project folder it won't appear as the highlights are saved per project folder. 

Are you doing anything different that may be causing them not to appear?

**Comment by marykaw** [comment]
Hi Brandon,

Ah thanks so much, I did not realise it was saved per project and was opening the file directly :)

Just taking a chance, Is there perhaps a way to keep the highlighting in check when inserting lines above the highlighted rows (it seems to be bound to the line and column numbers)?

**Comment by BrandonBlaschke** [comment]
No problem!

Yeah thats something I got to fix, I'm planning on trying to fix that soon here because I agree its something that would be nice to have. I appreciate the input.

**Comment by marykaw** [comment]
That would be awesome!  Thank you very much for the feedback.
Already looking forward to it :)

**Comment by BrandonBlaschke** [comment]
Hi Markykaw, 

Added moving highlights to the extension. There are a couple of issues with this implementation but I think it should work for most use cases and is an all around improvement from before.

Let me know if you have any other issues that you may come across that aren't already known.

**Comment by BrandonBlaschke** [comment]
Updated to 1.2.0.
